blank_lines_upper_bound = 2  # From 0.2.17
error_on_line_overflow = false
match_block_trailing_comma = true
newline_style = "Unix"  # Default.
reorder_imported_names = true
reorder_imports = false  # Default.
reorder_extern_crates = true  # Required for `reorder_imports = true`.
reorder_extern_crates_in_group = true  # Default.
trailing_comma = "Vertical"  # Default.
unstable_features = true

# This file is for =rustfmt-nightly-0.3.8 .
