required_version = "0.4.1"
unstable_features = true

blank_lines_upper_bound = 2
error_on_line_overflow = false
match_block_trailing_comma = true
newline_style = "Unix"  # Default.
reorder_extern_crates = true  # Required for `reorder_imports = true`.
reorder_extern_crates_in_group = true  # Default.
reorder_imported_names = true
reorder_imports = true  # Required for `reorder_imports_in_group = true`.
reorder_imports_in_group = true
reorder_modules = true
trailing_comma = "Vertical"  # Default.
wrap_comments = true
