[package]
name = "opaque_typedef_macros"
version = "0.0.1"
authors = ["YOSHIOKA Takuma <tashioka.256@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
quote = "^0.3.15"
syn = "^0.11.11"
strum = "^0.8"
strum_macros = "^0.8"
